live_config_reload = true
shell = { program = '/bin/zsh' }

[selection]
save_to_clipboard = true

[keyboard]
bindings = [
  { key = 'C', mods = 'Super', action = 'Copy' },
  { key = 'P', mods = 'Alt', action = 'Paste' },
  { key = 'Q', mods = 'Super', action = 'Quit' },
  { key = 'N', mods = 'Super', action = 'SpawnNewInstance' },
]
