require("core.rami")
require('core.autocmds')
require("core.options")
require("core.keymaps")

PLUG('fzf')
PLUG('cmp')
PLUG('mini')
PLUG('telescope')
PLUG('comment')
PLUG('lspconfig')
PLUG('treesitter')
PLUG('todo-comment')
PLUG('colorscheme')
PLUG('conform')
PLUG('neogit')


-- PLUG("plugins.lsp.config")

-- PLUG("plugins.autopairs")
-- PLUG("plugins.treesitter")
-- PLUG("plugins.mason")
-- PLUG("plugins.conform")
-- PLUG("plugins.fidget")
-- PLUG('plugins.telescope')
-- PLUG("plugins.cmp")
-- PLUG("plugins.neogit")
-- PLUG("plugins.schemastore")
-- PLUG("plugins.terminal")
-- PLUG("plugins.comment")
-- PLUG("plugins.md-preview")
-- PLUG("plugins.trouble")
-- PLUG("plugins.copilot")
-- PLUG("plugins.oil")
-- PLUG("plugins.neotree")
-- PLUG("plugins.colorizer")
-- PLUG("plugins.colorscheme")
-- PLUG("plugins.toggle-diagnostics")

-- PLUG('plugins.cellular-automaton')

-- PLUG("plugins.lualine")
-- PLUG("plugins.gitsigns")
-- PLUG("plugins.nvimtree")
-- PLUG("plugins.harpoon")

-- PLUG("plugins.devicons")
-- PLUG("plugins.whichkey")

require("core.lazy")

