require("core.rami")
require('core.autocmds')
require("core.options")
require("core.keymaps")

PLUG('fzf')
PLUG('cmp')
PLUG('mini')
PLUG('telescope')
PLUG('comment')
PLUG('lspconfig')
PLUG('treesitter')
PLUG('todo-comment')
PLUG('colorscheme')
PLUG('conform')
PLUG('trouble')
PLUG('lualine')
PLUG('autopairs')
PLUG('colorizer')
PLUG('gitsigns')
PLUG('copilot')
PLUG('terminal')
PLUG('neotree')
PLUG('markdown-preview')
PLUG('oil')

require("core.lazy")

